### PR TITLE
Cross platform: porting from .NET Framework to .NET Core.

### PR DESCRIPTION
**Pull request by laqieer**
Windows, Linux & OSX

### CODE REVIEW

**Comment by ipatix** [comment]
So if I understand correctly, this change is mostly related to optimize cross platform compatibility? Previously I used Mono, but I'm not sure if that's still a thing.

I haven't used any .NET languages in quite some time so I'm not that familiar with the changes of .NET Core. I'm fine with merging this, though, I wonder if there are relevant changes.

EDIT:
So at least I'm having issues compiling this:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.	m4a2s	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112	
```
How do I get a newer .NET core version?

**Comment by laqieer** [comment]
MacOS Catalina  has compatibility problems with Mono, Wine, Crossover and so on.
You can get .Net Core 3.1 [here](https://dotnet.microsoft.com/download/dotnet-core/3.1).

**Comment by ipatix** [comment]
Sorry for the delay...

Would it be a problem to use an older .NET core version which is still compatible with older VS versions? I'm looking at 1.1.
So unless the newer features aren't needed, I'd prefer to stay with an older version.

**Comment by laqieer** [comment]
I think it is okay to use an old .Net core.

**Comment by ipatix** [comment]
Again, sorry for taking so long. I know it sucks to make contributions to other projects and having to wait for such a long time.

I now tried this with dotnet core 2.1, which is the latest LTS version that still works with VS2017. The problem now is that it compiles a .dll instead of .exe file. How do I fix this?

EDIT:
Oh, so it seems this .dll compilation thing is intended like that:
https://stackoverflow.com/questions/44074121/build-net-core-console-application-to-output-an-exe

I will now commit my version with dotnet core 2.1.

**Comment by ipatix** [comment]
https://github.com/ipatix/m4a2s/commit/b86b7985dc49e78b5f32d74e3aa07399b4fa7c8d

**Comment by laqieer** [comment]
> I now tried this with dotnet core 2.1, which is the latest LTS version that still works with VS2017. The problem now is that it compiles a .dll instead of .exe file. How do I fix this?
> 
> EDIT:
> Oh, so it seems this .dll compilation thing is intended like that:
> https://stackoverflow.com/questions/44074121/build-net-core-console-application-to-output-an-exe
> 

.dll runs on all platforms, while .exe only runs on Windows, so I prefer .dll to .exe.

**Pull request closed without merging**
